# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up latest JDK
        uses: actions/setup-java@v2
        with:
          java-version: 'latest'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up latest JDK
        uses: actions/setup-java@v2
        with:
          java-version: 'latest'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test
